name: Run mock project
on: [push, workflow_dispatch]

jobs:
  run-test_project:
    name: Install NUTS and run test project using custom test class
    runs-on: ubuntu-latest
    services:
      box01:
        image: ghcr.io/network-unit-testing-system/nuts-testclient:latest
        options: >-
          --tty
        ports:
          - 2222:22
        env:
          ADMIN_PASSWORD: admin

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -vv
        working-directory: test_project
      